FROM node:22-alpine3.22

WORKDIR /usr/src/api

COPY package*.json ./

COPY prisma ./prisma/

RUN npm ci

RUN npm i -g nodemon

COPY . .

RUN npx prisma generate

EXPOSE 5000

CMD ["nodemon","-L", "server.js"]